### PR TITLE
Add Github Actions script to push a Docker image

### PR DESCRIPTION
**Pull request by giorgiosironi**
(needs test to be added after https://github.com/libero/scripts/pull/10)

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
(Not sure what test needs adding. Something that pushes a dummy repo?)

**Comment by giorgiosironi** [comment]
Yes, relying heavily on `docker` commands it's the only way to test the interaction with a Docker registry. May be able to run a registry as a dummy, otherwise have to rely on Docker Hub.

**Comment by giorgiosironi** [comment]
Disabling the required checks from https://github.com/libero/scripts/settings/branch_protection_rules/2842606 until the names are more stable, this time "static" checks doesn't cover actual execution of the scripts.

**Comment by giorgiosironi** [comment]
The dummy registry worked on the first try; cleanly terminates resetting all the state of pushed images.

**Review by thewilkybarkid — APPROVED** [review]

**Pull request merged**
