### PR TITLE
Add travis/downstream.sh script

### PR DESCRIPTION
**Pull request by giorgiosironi**
A Travis CI build may need to trigger downstream builds of other repositories. For example, after a `browser` or `pattern-library` new commit on `master`, we eventually trigger `environments` to redeploy them.

This script is [extracted from browser](https://github.com/libero/browser/blob/master/.travis/downstream-environments.sh) and provides an API call that triggers another `libero/` build on its `master` branch. There isn't space for passing arguments to that build apart from a message which is an annotation on why that build is happening.

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
I know this already exists in Browser etc, but time to try out Dependabot (with auto-merging)? Not sure how quick their live PRs are...

**Comment by giorgiosironi** [comment]
Does it deal with this use case? This is a Travis CI build triggering another build after tests have passed, while `environments` doesn't have a `composer.lock` or similar dependencies; only a default `.env.dist` used for the first checkout.

**Comment by giorgiosironi** [comment]
I think they probably deal with the update of submodules, not sure about the update this script is triggering.

**Comment by thewilkybarkid** [comment]
Haven't look into the details of `environments` before. So it's meant to be able to handle lots of set of environments, currently just https://github.com/libero/sample-configuration? Seems like the latter should be actually pinned. So, that could be updated. However, turns out Dependabot doesn't yet handle Docker Compose (https://github.com/dependabot/feedback/issues/82), so would currently need local `Dockerfile`s that just extend the real image. If https://github.com/libero/environments/blob/e50f4d3806620b76c48e55ff5702a719669890e7/scripts/remote-deploy.sh#L6-L13 became a proper submodule, that can be auto updated. If not, can still have this trigger on `sample-configuration`. But, not entirely sure of the distinct between these two repos: `environments` is a _library_ for `sample-configuration` to deploy itself?

**Comment by giorgiosironi** [comment]
`sample-configuration` is the equivalent of a formula/Helm chart/`elife-xpub-deployment`: a portable repository that can be used to deploy Libero in some configuration (a simple one) almost anywhere. The main targets so far are locally (for testing), Travis CI builds, and a single server `unstable` (there could be more).

`environments` introduces credentials to deploy to Libero AWS account (and possibly anywhere else Libero projects should be hosted). The only target right now is `unstable.libero.pub`, a single EC2 instance. I plan for more, for example a `stable` one that deploys the latest `1.x` tags, or other customizations like:
- a `stable-aws` that uses RDS and other AWS-specific stuff
- a `stable-gke` that deploys on Kubernetes etc
Not all of these environments may use `sample-configuration`, as it's stricly related to `docker-compose` (as soon as there is another one should be renamed to `sample-configuration-docker-compose`).

`sample-configuration` at the moment doesn't pin the versions of containers, only [providing defaults](https://github.com/libero/sample-configuration/blob/master/.env.dist). I think those default tags should become `latest`, but it's just that we don't push that tag yet. We probably should by now, or use a separate prefix or separate repository or separate tag `develop` that shows they are bleeding edge.

`remote-deploy.sh` is [uploaded to the target server](https://github.com/libero/environments/blob/e50f4d3806620b76c48e55ff5702a719669890e7/scripts/deploy.sh#L15), so there's not Git repository there to put `sample-configuration` into as a submodule. The current deployment is very dumb however, it checks out the `master` branches of projects and tells `remote-deploy.sh` to use tags names like their commits.

In general we are starting to need a state storage for the versions of what is deployed on which environment. Travis CI doesn't cut it by itself, the second option is GitOps (committing them into a Git repository whether it is `sample-configuration` or another one), we should evaluate more alternatives. For an `unstable` environment a script that continues to look at the `master` branches works, but doesn't scale to the general problem.

**Comment by giorgiosironi** [comment]
This is now required by `pattern-library` [to trigger `environments`](https://github.com/libero/libero/issues/84)

**Comment by GiancarloFusiello** [comment]
@giorgiosironi Rather than having a script do this, can this be part of the pipeline after merging to master for those repositories you mentioned?

**Comment by giorgiosironi** [comment]
The script is called as part of the pipeline of merging to `master`, in the `deploy` section:
https://github.com/libero/browser/blob/master/.travis.yml#L30
(this is an example that uses the non-generic version of this script, should point to this one in the future)

**Review by GiancarloFusiello — APPROVED** [review]

**Comment by giorgiosironi** [comment]
Can't merge anyway due to a maintainer needing to approve...

**Review by thewilkybarkid — APPROVED** [review]
Already in use so we can merge. My preference is still for this to be done externally though.

**Comment by giorgiosironi** [comment]
A Dependabot-like `docker-compose`-oriented auto update would be ideal to outsource this, but even that at the moment doesn't provide guarantees on latency.

**Pull request merged**
